### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by chrisgettowork** [thierryc/Sketch-Find-And-Replace#100]
I want to replace a ”sentence“ with another ”sentence“,but it doesn't work.
It seems that only can replace the Word at present？

**Comment by thierryc** [comment]
Can you update to 59 ? 

If you can't:

Download an older version. 

https://github.com/thierryc/Sketch-Find-And-Replace/releases

The last v1 version is the 1.25. 

https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.25

Best regards
Thierry

**Comment by chrisgettowork** [comment]
Thanks for your suggestion.
I update my sketch version to 59,and replace the older version plugin.It seems that only can replace the Word at present,right？
Actually my real question is that I can't replace a sentence by another sentence.

**Comment by thierryc** [comment]
You can replace what you want. Word, sentence, etc... You can use regex too.
