### ISSUE TITLE
Update via Sketch Update-Button does not work properly

### ISSUE THREAD

**Issue by uidproberlin** [thierryc/Sketch-Find-And-Replace#103]
Update via Sketch Update-Button does not work properly (Sketch Version 61.2 (89653))

**Comment by thierryc** [comment]
Thank you to report. I will fix it.

**Comment by thierryc** [comment]
@uidproberlin, Please try it again... the 2.8.0 is online. The update should work now. 

Thierry

**Comment by thierryc** [comment]
Ps: sketch 62 is out. ;-)

Cmd shift f is used to find some symbols.

To active Find and Replace, you should use : New Shortcut : "cmd option shift f"

**Comment by thierryc** [comment]
@uidproberlin 
the Update-Button working for you now?

Best

**Comment by imfh** [comment]
The update button does not work for me yet.

Sketch v.62

**Comment by richardsison** [comment]
Same with me. It's saying 2.8.2 is available but I can't update to it. Downloading the version from Github is also 2.8.0 (which was the fix last time…)

**Comment by uidproberlin** [comment]
Its working for me Version 62 (91390)

**Comment by uidproberlin** [comment]
Thanx
