### ISSUE TITLE
"Plugin Update Available" - but won't update

### ISSUE THREAD

**Issue by timtops** [thierryc/Sketch-Find-And-Replace#104]
Not sure if this is a Sketch (Version 62 (91390)) issue or a plugin (v2.8.0) issue... 

- Sketch show the orange "Plugin Update Available" button/message up in the top right corner
- F&R is the only plugin that apparently needs updating (to 2.8.2)
- The blue "Update" button in the Sketch Preferences dialogue doesn't do anything
- I tried removing the old plugin and installing fresh from Github and restarting Sketch multiple times but all to no avail

Apologies if this is a Sketch issue. 

Thanks
Tim

**Comment by mwevdmeer** [comment]
The latest release of the plugin has version 2.8.0, so downloading the latest release just reinstalls that version instead of 2.8.2

**Comment by timtops** [comment]
Aa, that would be it. I did wonder if that was possible.

**Comment by thierryc** [comment]
@timtops it is working now. It work for me.

**Comment by mwevdmeer** [comment]
> @timtops it is working now. It work for me.

Confirmed, it's working now. Thanks!

**Comment by uidproberlin** [comment]
Version 62 (91390) / 2.8.0: Sketch UPDATE Button NOT WORKING properly

**Comment by timtops** [comment]
Confirmed! Thank you :) That orange "Plugin Update Available" button was blinding me! ;)

**Comment by timtops** [comment]
> Version 62 (91390) / 2.8.0: Sketch UPDATE Button NOT WORKING properly

You might need to restart Sketch?

**Comment by thierryc** [comment]
> Version 62 (91390) / 2.8.0: Sketch UPDATE Button NOT WORKING properly

If the restart sketch doesn’t fix your issue, you may update it manually. 

https://github.com/thierryc/Sketch-Find-And-Replace/releases
