### ISSUE TITLE
Find and Replace not working anymore

### ISSUE THREAD

**Issue by SketchyCraig** [thierryc/Sketch-Find-And-Replace#108]
It looks like this last Sketch update(or Mac OS update if that's possible) Broke find and replace. I can't get it to work any more since I restarted a few days ago.

**Comment by thierryc** [comment]
Uninstall and download (re)install the plug-in.

https://github.com/thierryc/Sketch-Find-And-Replace/releases/download/v2.11.1/Find-and-replace.sketchplugin.zip

To install: download this file, unzip and double click on the .sketchplugin

<img width="530" alt="find-and-replace" src="https://user-images.githubusercontent.com/197471/78794736-1e57c780-7982-11ea-86ed-ebcf57817654.png">

**Comment by thierryc** [comment]
What is your sketch version ? 64 ?

**Comment by SketchyCraig** [comment]
I thank you, and my co-worker thanks you. ☺

**Comment by SketchyCraig** [comment]
Yes, 64. But reinstalling seems to have fixed it.
