### ISSUE TITLE
Plugin doesn't work.

### ISSUE THREAD

**Issue by LinaChetverkina** [thierryc/Sketch-Find-And-Replace#110]
Hey guys,

I am on version 67.2 of Steck and the plugin doesn't work for me. Please help!

**Comment by thierryc** [comment]
What is your Find and Replace version? 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/197471/88048785-f6036b80-cb21-11ea-90c4-0a178ba36b26.png">

To get it: click on the (?) 

What text you want to replace? Do you have an example?

**Comment by LinaChetverkina** [comment]
Hi there,

The version is 2.11.1, trying to remove the word 'Copy' with space

**Comment by thierryc** [comment]
In the name of your layer?... this plug-in is not made for. 
Use rename-it plugin.
