### ISSUE TITLE
Not working in sketch 67

### ISSUE THREAD

**Issue by keano123** [thierryc/Sketch-Find-And-Replace#111]
I can't get the plugin to work. I do this and nothing happens.
![Screen Shot 2020-07-20 at 8 15 20 PM](https://user-images.githubusercontent.com/68089930/88008717-c32b8a00-cac5-11ea-9e03-365c869db44e.png)

**Comment by thierryc** [comment]
Hello, you want to rename the **layer name** not to replace **the text** like LargeTitle -> TitleLarge... 

To do that use rename it plugin: https://renameit.design/sketch/
