### ISSUE TITLE
Non-alphabetic language not working

### ISSUE THREAD

**Issue by sypark22** [thierryc/Sketch-Find-And-Replace#112]
Hello,

After updating Sketch to 67.2, it seems like Find and Replace is not working with non-alphabetic languages, or at least Korean.
I'm a Korean user and I had no problem with replacing Korean language before updating.
English works fine, but I think some alphabets with accent are not working either. (For example, French è, é, ê, à)
I tried reinstalling the plugin but it's still not working. 

<img width="965" alt="Screen Shot 2020-07-22 at 11 27 21 AM" src="https://user-images.githubusercontent.com/68625162/88127349-58d23100-cc0e-11ea-838b-4ae9aa54df53.png">
<img width="443" alt="Screen Shot 2020-07-22 at 11 27 26 AM" src="https://user-images.githubusercontent.com/68625162/88127362-612a6c00-cc0e-11ea-83ff-6a8aeca9d526.png">

Thank you.

**Comment by thierryc** [comment]
Hi, may I have a sketch test file in your language to test it?
