### ISSUE TITLE
Uploaded Plugin but when I try to use it no 'find and replace' screen comes up. It shows up in my list of plugins but when clicked does nothing. 

### ISSUE THREAD

**Issue by RiDvs** [thierryc/Sketch-Find-And-Replace#113]
Uploaded Plugin but when I try to use it no 'find and replace' screen comes up. It shows up in my list of plugins but when clicked does nothing.

**Comment by thierryc** [comment]
Hi,  May I have more information please?

Sketch version and OS version.  

You may try to remove it from your sketch plugin folder and download it  and install it again. 

Goto preferences -> plugins.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/197471/91079435-0a032700-e612-11ea-93df-fa057925beb0.png">

Delete the file "Find-and-replace.sketchplugin"
and Replace it by this one: https://github.com/thierryc/Sketch-Find-And-Replace/releases/download/v2.11.1/Find-and-replace.sketchplugin.zip

**Comment by RiDvs** [comment]
Hello, thanks for your quick response sorry I got delayed coming back to you. Attached is the info about my sketch, I need to renew the licence... hadnt realised it had expired.
Could be why its not working, did try and re-install it but still nothing happens when I click on it in my plugins.

________________________________
