### ISSUE TITLE
The plugin is probably not supported with Sketch 70+

### ISSUE THREAD

**Issue by Or1005** [thierryc/Sketch-Find-And-Replace#114]
:(
Sketch version: 70.2
Plugin version: v2.6

**Comment by thierryc** [comment]
It works on my side. 
What is your version of OS?

**Comment by thierryc** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/197471/101387366-58b89200-388c-11eb-9043-9f7ba4aaf028.png">

**Comment by thierryc** [comment]
No other feedback? 
I close this issue.

Be free to (re)open it, if you get the same issue.
