### ISSUE TITLE
Why text set in auto width breaks in two line?

### ISSUE THREAD

**Issue by jivanshr** [thierryc/Sketch-Find-And-Replace#14]
I want to replace time with money,You can refer images to know the issues

**both text are set on auto.**

Before:
<img width="260" alt="screen shot 2016-08-02 at 5 01 44 pm" src="https://cloud.githubusercontent.com/assets/4607569/17326692/a1543c74-58d2-11e6-9eb9-4435f6ca614b.png">

After:
<img width="260" alt="screen shot 2016-08-02 at 5 01 28 pm" src="https://cloud.githubusercontent.com/assets/4607569/17326691/a01868b2-58d2-11e6-9b5b-c1aba3dd6f32.png">

**Comment by thierryc** [comment]
Fix the size of you text box to fit your design before you apply the Sketch-Find-And-Replace.
