### ISSUE TITLE
When Matching Partial Text, The Formatting For The Entire Text Block Is Affected.

### ISSUE THREAD

**Issue by brandonkboswell** [thierryc/Sketch-Find-And-Replace#16]
In This Scenario I search for all Instances of 36 and ask them to be changed to 37's. When they are the Text Styling of the trailing text is lost.

<img width="782" alt="screen shot 2016-10-10 at 4 39 35 pm" src="https://cloud.githubusercontent.com/assets/921925/19250419/2e29128a-8f08-11e6-8784-1a1bcd61432b.png">

**Comment by bmoondesign** [comment]
I have the same issue, please fix :)

**Comment by jasonogle** [comment]
Yep, same here.

I would love to be able to replace multi-line text that has different styles without changing the style. I'm sure some of this may be inherent to Sketch, but would be awesome if there was a way around this.

It's forcing me to just not have different styles in my text which is great when I'm creating the Sketch files, but if I want to find/replace someone else's (like now), I'm out of luck.

Thanks for creating this incredible tool!

**Comment by thierryc** [comment]
I have no solution for the moment.
