### ISSUE TITLE
Multi-line replace changes styles

### ISSUE THREAD

**Issue by jasonogle** [thierryc/Sketch-Find-And-Replace#17]
I would love to be able to replace a single line of text in multi-line box that has different styles without changing the style of all the text in the box. I'm sure some of this may be inherent to Sketch, but would be awesome if there was a way around this.

It's forcing me to not use any additional text styles in my text-boxes which is great when I'm creating the Sketch files–but if I want to find/replace someone else's (like now), I'm out of luck.

Thanks for creating this incredible tool!

**Comment by mscodemonkey** [comment]
Yeah that's a real problem with Sketch, there's no easy way of getting around the issue that when you replace text it uses the style that's in the selector for that layer.  Saying that I have written a standalone piece of code that sort of works but will need a lot of refinement before it's ready to even go into the plugin.  Stay tuned :-)

**Comment by thierryc** [comment]
I close for the moment. Reopen it, if the sketch API change.
