### ISSUE TITLE
Not working with Sketch v42

### ISSUE THREAD

**Issue by leannegunn** [thierryc/Sketch-Find-And-Replace#21]
This used to work GREAT, but in the last couple updates of Sketch notice it's no longer working. Are there any plans to continue maintaining, just so users can know if we need to look for a replacement? Thank you!

**Comment by mscodemonkey** [comment]
Sorry have neglected this plugin due to work commitments, but have a little spare time to look at the bugs and requests now.  I'm running 42 and it appears to be fine.  What's not working on yours?

**Comment by ArtimusPrime99** [comment]
I just found this plug-in. Thanks! Just to follow up on the above issue... Works fine if I'm replacing all text within text block, but not if I want to replace some of the text within a text block.

**Comment by charlie5188** [comment]
Well, this plugin still works for alphabet, but doesn't work for other languages like Chinese, Japanese and Korean.

**Comment by kevinmcbride** [comment]
I'm having this issue too.  Worked in the past, but just tried on Sketch 42 and does not seem to work at all.  Anyone have suggestions?

**Comment by rodnem** [comment]
Yeap, it doesn't work when trying to replace a word inside a paragraph

**Comment by thierryc** [comment]
Unselect the text in the paragraphe before.

**Comment by kaiser-jakob** [comment]
It is working with selected layers for me. but not with current page/whole document. sketch 45.1 and plugin version 1.7

**Comment by thierryc** [comment]
Let me try.

**Comment by thierryc** [comment]
I work on it

**Comment by thierryc** [comment]
It rocks ... please test it. 
1.8...  automatique Update !

**Comment by thierryc** [comment]
Get it !

https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.8

**Comment by mrbelding76** [comment]
I have noticed that when i select a "$" currency symbol to replace it with an international currency on a document with something lik a "€" symbol, the "€" symbol appears at the end of every text field and does not replace the "$" at all. BUT going from a "€" symbol to a "£" = no problems at all. thoughts?

**Comment by thierryc** [comment]
let me test.
