### ISSUE TITLE
Dialog inputs focus

### ISSUE THREAD

**Issue by tbnv** [thierryc/Sketch-Find-And-Replace#22]
Hi,

Would it be possible to set the focus on the first input when the dialog opens? And also to allow using tab to quickly go to the second input? 

Keeping hands on the keyboard when using the plugin, that would be really convenient. ⌨️ 👐 

Regards,
Thibaut

**Comment by seandellis** [comment]
@tbnv Good news! Keyboard focus and the tab key now work.

Bad news. The plugin no longer works with Sketch 45. Hopefully that can get resolved soon.
