### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mischugo** [thierryc/Sketch-Find-And-Replace#24]
Any chance to have the option for "find only", placed in a list?
And then from there, a link to the appropriate layer :-)

Best!!!

**Comment by rodnem** [comment]
Or simply a selection of the found layers on the same page

**Comment by seandellis** [comment]
Duplicate of #18

**Comment by thierryc** [comment]
Assigned to me in #18. I close this issue. Thank you @mischugo
