### ISSUE TITLE
Not working in Sketch 43.2

### ISSUE THREAD

**Issue by Petros-** [thierryc/Sketch-Find-And-Replace#26]
Hi, I've used this plugin in the past with delight, but alas it's no longer working for me. Here's the trouble I'm running into, would you be willing to take a look?
Repro steps
- Have text in symbols on the symbols page that I want to replace
- Access the plugin Plugins > Find and Replace > Find and Replace
- Enter the text I want to replace and what I want to replace it with
- Observe the results: none of the specified text changes.

Sketch version 43.2 (39069)

I appreciate the work you put into developing this plugin and am hopeful you'll be able to find time to look into the issue I mentioned. Thanks!

**Comment by seandellis** [comment]
@Petros-  The latest version of the plugin now supports symbol overrides. Try grabbing the new version.
