### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mischugo** [thierryc/Sketch-Find-And-Replace#33]
I have a big text box (table/list)) with currencies.
I have to change all "." to a "," ...

The is current no chance to do that, right.
Whats a bout a feature then, where i can change any letter in the selected layer(s)?

Cheers

**Comment by thierryc** [comment]
**Regex search** - Implement a full regex-based search for power users.

**Comment by thierryc** [comment]
Regex beta version is ready ! 
Test it !

https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.9-beta

**Comment by thierryc** [comment]
I have a good news  for you ! 
Try the last beta release: 

https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.9-beta2

enter in find: (\d+).(\d+)
enter in replace: $1,$2

Select regex yes radio button.

GO !

Or try more fun regex like: 

Date in format dd/mm/yyyy
```
(0?[1-9]|[12][0-9]|3[01])([ \/\-])(0?[1-9]|1[012])\2([0-9][0-9][0-9][0-9])(([ -])([0-1]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9])?

```

Hex Color Value
```
#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})
```
