### ISSUE TITLE
Update or maintain this code

### ISSUE THREAD

**Issue by thierryc** [thierryc/Sketch-Find-And-Replace#36]
Dear Martin,

Sean Dellis and Me are able to update or maintain this code if you want.

You don't use Sketch any more ? 
Why ? What is your new favorite tools ? 

Best regards
Thierryc

**Comment by seandellis** [comment]
@mscodemonkey We'd love to help maintain this project. Please let me and @thierryc know how you'd like to handle the transfer.

**Comment by mscodemonkey** [comment]
Hey Thierry 

Not sure how I go about transferring the project to you guys?

**Comment by mscodemonkey** [comment]
Hey sean

Not sure how I do that transfer?

**Comment by mscodemonkey** [comment]
Oh the reason I don't use sketch is not that I have anything better, just moved on within the company so not hands on design anymore.

**Comment by thierryc** [comment]
Hi, Martin, 

We can get your plug-in up-to-date if you hands on design.
You can transfer the project in the preferences in the Danger Zone.

We can create a organization like « project group » to host the project altogether. 

Do you have a suggestion for the groupe. 

1. Sketch-Simple-Plugins
2. Sketch-Monkey-Plugins
3. ?

Best
Thierry

**Comment by mscodemonkey** [comment]
I transferred it to thierryc as seandellis already has a version and it wouldn't let me transfer it there.

Thanks guys, much appreciated!

**Comment by thierryc** [comment]
Perfect Thank you.

**Comment by thierryc** [comment]
@seandellis I send you an invitation.
