### ISSUE TITLE
Doesn't work on Chinese

### ISSUE THREAD

**Issue by steveluoxin** [thierryc/Sketch-Find-And-Replace#46]
Is it just me or this plugin doesn't work on Chinese?

**Comment by steveluoxin** [comment]
My mistake. I uninstalled the plugin and then reinstalled. Now it's working perfectly.

**Comment by thierryc** [comment]
Well ! Good news. 

I need help for translation: the interface + readme in Chinese.

**Comment by steveluoxin** [comment]
Well. I think I can help : )

**Comment by thierryc** [comment]
Well, I am going to add a translation system to the plug-in. 
I will send you the sentence list. 

Thank you very much.

**Comment by steveluoxin** [comment]
OK! Let's do it.
