### ISSUE TITLE
UN-bolds, UN-underlines, and UN-colors surrounding text.

### ISSUE THREAD

**Issue by bgott** [thierryc/Sketch-Find-And-Replace#48]
My text body contains partially-colored, partially-bold, and partially-underlined phrases, and running the find-and-replace plugin unformatted these phrases.

**Comment by thierryc** [comment]
It is a limitation of the sdk. I try to find a solution. Help is wanted.

**Comment by mattstudio** [comment]
I wrote a sketch plugin that replaces the numbers inside any text layer with random numbers and finally found a way to solve this. This is the function that I found that preserves the formatting while still replacing the the text:

[layer replaceTextPreservingAttributeRanges: "" + randomNum];

Hope this helps!

**Comment by thierryc** [comment]
Let me try it ! thank you

**Comment by thierryc** [comment]
Please try this version : https://github.com/thierryc/Sketch-Find-And-Replace/tree/replaceTextPreservingAttributeRanges

**Comment by thierryc** [comment]
@mattstudio It works for me. Please try it. https://github.com/thierryc/Sketch-Find-And-Replace/tree/replaceTextPreservingAttributeRanges

**Comment by thierryc** [comment]
It works only if source text and replace text are close. (the same length).

**Comment by thierryc** [comment]
#49

**Comment by thierryc** [comment]
Sketch-Find-And-Replace 1.13
https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.13

Thank you to @mattstudio and @bgott

**Comment by thierryc** [comment]
Sketch-Find-And-Replace 1.13 fix this issue
