### ISSUE TITLE
RegEx not working in Sketch 47

### ISSUE THREAD

**Issue by evosyn** [thierryc/Sketch-Find-And-Replace#55]
RegEx expressions are not resulting in changes being made in Sketch 47

Attempting both examples in the Read.me don't work

**Comment by thierryc** [comment]
Fixed! Please test it. Happy Thanksgiving

**Comment by evosyn** [comment]
Most commands are working! Thank you.

I'm running into one issue: Using this string to find spaces at the beginning of text layers `^\s` and replacing them with no space (to remove the space). It doesn't seem to work with the `^` modifier, but does work with just`\s`

Thoughts?

**Comment by thierryc** [comment]
Let me open a new issue for this. #57.
