### ISSUE TITLE
Find & Replace on current page / whole document - Skips selected layer :(

### ISSUE THREAD

**Issue by luciatplangrid** [thierryc/Sketch-Find-And-Replace#62]
Sometimes when I do "Find & Replace on current page" or "Find & Replace in whole document" it will replace all instances EXCEPT the one in the currently selected layer.

**Comment by thierryc** [comment]
Your text layer is in the edit mode ?

**Comment by luciatplangrid** [comment]
That is correct. The issue occurs if the text layer is selected / in the
edit mode when I open the plug-in.

Thanks,
Luci

**Comment by thierryc** [comment]
Thank you. I will try to fix it.
