### ISSUE TITLE
Plugin doesn’t work with documents containing artboard symbols

### ISSUE THREAD

**Issue by l-i-n-k** [thierryc/Sketch-Find-And-Replace#67]
Sketch 50.2 and Plugin version 1.24

As soon as you create a symbol from an artboard the plugin won’t work at all. We use artboard symbols, for example, to prototype several overlays on pages.

**Comment by thierryc** [comment]
Hello, 
Do you have any sketch file example ?

**Comment by thierryc** [comment]
Add Find and replace in the symbols support. 
For symbols in the symbols page or not. 

Add an option in conf. to prevent replace placeholder name.

**Comment by thierryc** [comment]
Current solution : 
Use the select layer option.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/197471/41540180-90272be2-72dd-11e8-99d5-59ff6e2522f6.png">


<img width="1519" alt="image" src="https://user-images.githubusercontent.com/197471/41540127-7a7c2ff4-72dd-11e8-803c-b334b92cb754.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/197471/41540211-9ee1cbc4-72dd-11e8-96e6-5795a02a80ab.png">

**Comment by thierryc** [comment]
1.25 is out !

<img width="842" alt="image" src="https://user-images.githubusercontent.com/197471/41541068-90eb74f0-72df-11e8-8b97-24ef1eceff9a.png">

**Comment by l-i-n-k** [comment]
Thanks. It’s possible to select all symbol artboards and trigger Find/Replace. I wasn’t aware of this. One has to make sure that you do that if replace fails.

![screen shot 2018-06-18 05 37 05 pm](https://user-images.githubusercontent.com/784287/41546763-c8b9f53e-731e-11e8-90c3-0de314db60c7.png)

**Comment by thierryc** [comment]
Yes, you can ! 
But replace text in symbols is dangerous. 
You may replace a placeholder too. It is for advanced users only. 

Cmd Z can save your life ! ;-)

**Comment by Johnathangalliano** [comment]
@thierryc I am not able to rename any symbol names. All other plugins have been deactivated to rule out conflict.

Please advice. 

![screen shot 2019-01-09 at 16 56 22](https://user-images.githubusercontent.com/4027818/50911419-21d36a80-1430-11e9-9ba0-cb88c8dcedec.png)
