### ISSUE TITLE
hope to support Chinese characters 

### ISSUE THREAD

**Issue by wesleylin** [thierryc/Sketch-Find-And-Replace#7]
find and replace is a great sketch life saving plugin. 
However, i found it can replace English perfectly but failed to do it with Chinese. 
hope to support Chinese characters.
it will save millions of Chinese UI designers' lives.

**Comment by itcook** [comment]
@wesleylin 
Try to select the 'Yes' option of 'Match whole words or phrases only', it works to me.

**Comment by wesleylin** [comment]
@itcook Problem solved. Thank you very much.

**Comment by thierryc** [comment]
I close this #27

Does not find Cyrillic letters #5
Can't replace Chinese strings #27
Unsupport chinese ？ #13
