### ISSUE TITLE
Find and Replace in Library instance default text?

### ISSUE THREAD

**Issue by trustella** [thierryc/Sketch-Find-And-Replace#73]
Love your plug-in, but I wasn't able to use to replace text in a symbol instance from a Sketch Library. Is this something that you could add?

Repro:
1. Insert a button symbol from a Sketch Library. Default button copy is "Hello World"
2. Do Find-Replace for "Hello"

Result:
No instances replaced.

**Comment by thierryc** [comment]
The plugins can't replace the default message. You can select the master and find and replace Hello on the selected dartboard.
