### ISSUE TITLE
Replace parenthesis

### ISSUE THREAD

**Issue by venounan** [thierryc/Sketch-Find-And-Replace#75]
I'm trying to replace the string (PDF) but when I do, the find/replace ignores the () and just replaces the letters. Adding the term in quotations doesn't do anything either.

**Comment by thierryc** [comment]
Let my try.

**Comment by thierryc** [comment]
It is a bug. I will fix it soon. 
A trick for you: use regex. 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/197471/45160994-cca0f700-b1b8-11e8-8963-8e5693ac57c3.png">

**Comment by venounan** [comment]
Perfect, the Regex worked for me for the time being, thank you so much!

**Comment by thierryc** [comment]
Your welcome.

**Comment by thierryc** [comment]
Set the Match whole words or phrases only to yes. 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/197471/45197432-30fe9d80-b22f-11e8-8dd4-78659b6f93c1.png">
