### ISSUE TITLE
When I run replacing text, the text in the symbol got messed up with unknown series number

### ISSUE THREAD

**Issue by wangzhen0614** [thierryc/Sketch-Find-And-Replace#79]
**Steps to reproduce:**
1. open the plugin
2. Enter the text to find and replace
3. **Expected results**: only the text matched search gets replaced
4. **Actual results**: symbols with text get messed up with unknown series number
![jan-17-2019 16-15-32](https://user-images.githubusercontent.com/6403036/51352493-659f2300-1a73-11e9-89ea-678859c84e1e.gif)

**Comment by wangzhen0614** [comment]
It seems the problem only happens if the text style in the symbol gets swapped (the new feature in sketch 52 where you can apply different style to each element in the symbol)

**Comment by thierryc** [comment]
Thank you for this issue. Yes, it is. 
This bug is listed "Plugin hi-jacking non-matching symbol text #76" and it will be fixed in the v2. V1 is built over the CocoaScript API. 

The new v2 will be built over the JS API. Follow me on twitter to be posted.

**Comment by thierryc** [comment]
#76

**Comment by thierryc** [comment]
#76

**Comment by thierryc** [comment]
issue #76

**Comment by thierryc** [comment]
![image](https://user-images.githubusercontent.com/197471/51369776-17caff00-1af5-11e9-9ac6-271d937820bc.png)

**Comment by jane00** [comment]
v2 can not start up, oops

**Comment by thierryc** [comment]
@jane00 do you restart sketch ? 
Please try the last one. https://github.com/thierryc/Sketch-Find-And-Replace/archive/2.0.2.zip

**Comment by thierryc** [comment]
@jane00 

https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/2.0.3

**Comment by thierryc** [comment]
https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/2.0.4

<img width="462" alt="image" src="https://user-images.githubusercontent.com/197471/55022810-c7c75780-4fd1-11e9-8740-dd45077b2368.png">

**Comment by thierryc** [comment]
@jane00 your version start up now ?

**Comment by jane00** [comment]
Thank you for your reply. I start the dev tool and catch the erros:
![图片](https://user-images.githubusercontent.com/2392637/55122367-aaad9880-5139-11e9-8a59-3273608516c7.png)

**Comment by jane00** [comment]
TypeError: UI.getTheme is not a function. (In 'UI.getTheme()', 'UI.getTheme' is null)

**Comment by thierryc** [comment]
you can try the 2.0.7

**Comment by thierryc** [comment]
@jane00

Do you have test the 2.0.7 version

**Comment by jane00** [comment]
Thanks. I can open the v2.0.7.
But the replace for overrides does not works. Nothing was replaced.

And another suggestion is，  sometimes， only find and jump location to the found item is useful. Just like the find feature of Excel/Offiece. User wants to make sure which one will be replaced.

**Comment by jane00** [comment]
OSX 13.6
Sketch 52.6
thanks.

**Comment by thierryc** [comment]
The v2 start to work on the 53. 

"And another suggestion is， sometimes， only find and jump location to the found item is useful. Just like the find feature of Excel/Offiece. User wants to make sure which one will be replaced." 
Yes, it is on my todo.

**Comment by thierryc** [comment]
@!jame00, thank you for your feedback I will try to fix it for the 52... but if you can update to the 53.2.

**Comment by thierryc** [comment]
done
