### ISSUE TITLE
Finding and replacing string that contains special characters like "$" or "+" doesn't work

### ISSUE THREAD

**Issue by Korayem** [thierryc/Sketch-Find-And-Replace#8]
I tried several times and doesn't work

**Comment by barts** [comment]
I'm having this same problem. Trying to replace "Watch..." with "Watch" to remove the ellipsis, but it's not able to find it. If I just search for "Watch" and replace it with a different word, it works.

**Comment by seandellis** [comment]
The latest version of the plugin seems to work. Be sure that you have enabled "Match whole words or phrases only". See image for reference.

![screenshot 2017-05-18 01 18 38](https://cloud.githubusercontent.com/assets/1584916/26189027/260d4d98-3b68-11e7-9cb5-68d0bb59d72f.png)
