### ISSUE TITLE
Find and Replace affecting symbol overrides

### ISSUE THREAD

**Issue by aentan** [thierryc/Sketch-Find-And-Replace#80]
Whenever I do a Find and Replace, my icon symbols (using color symbol mask) gets overridden to a default color.

Here's a screencast of it happening http://aen.is/6174fdb12b50

**Comment by thierryc** [comment]
Thank you for this well-documented issue.
Do you have the file for my tests ?

v2 are coming...

**Comment by thierryc** [comment]
solved 
https://github.com/thierryc/Sketch-Find-And-Replace/releases
