### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by ghanesh-rs** [thierryc/Sketch-Find-And-Replace#9]
When I tried to find & replace it said  no instances found Ref Pic below

![image](https://cloud.githubusercontent.com/assets/17617240/13496316/7c60fe2c-e175-11e5-8ab1-dd0a149accb9.png)

So i tried changing it to match whole words then it did something weird plz chk img below

<img width="1170" alt="screen shot 2016-03-03 at 7 24 55 pm" src="https://cloud.githubusercontent.com/assets/17617240/13496349/b7296e72-e175-11e5-85c6-cf7a9a4d2196.png">

Issue is.. instead of jus replacing the text characters it changed the color & style of the words next to the searched characters as well which isnt what i wanted..

<img width="857" alt="screen shot 2016-03-03 at 7 25 12 pm" src="https://cloud.githubusercontent.com/assets/17617240/13496357/bf2c950e-e175-11e5-9fb4-1794a21e205e.png">

How to fix this ?

**Comment by mscodemonkey** [comment]
This is something i'm working on.  It's sort of a limitation of Sketch that if you replace the text in a layer it reapplies the first style that it finds in that text layer.  But i've got a standalone piece of code sort of working, just needs some refinement and then integrating with the plugin.

**Comment by thierryc** [comment]
I have no solution for the moment.
