### ISSUE TITLE
Plug in doesn't update

### ISSUE THREAD

**Issue by tzekin** [thierryc/Sketch-Find-And-Replace#94]
Sketch update plug-in dialog says a new version 2.0.10 is available but it doesn't download. Manually installing the latest version keeps telling me there is an update.

I have seen this problem with many plug ins the problem that do not report the correct version at all places in the code.

**Comment by Microburo** [comment]
Hello, same here.

**Comment by rodnem** [comment]
another one bites the dust

**Comment by bricelp** [comment]
Same here folks :)

**Comment by SolderHQ** [comment]
Same here 👍 Happened after updating to Sketch 54.

**Comment by tijmenvangurp** [comment]
same here

**Comment by thierryc** [comment]
I will fix it. Manual install works.

**Comment by thierryc** [comment]
Thank you for your help @tzekin @Microburo @rodnem @bricelp (capitain) @SolderHQ @tijmenvangurp.

**Comment by bricelp** [comment]
Thank's to you matelot ;)

**Comment by Microburo** [comment]
Salut Thierry, merci pour le debug de ce très bon plugin, qui est utilisé tous les jours.

**Comment by thierryc** [comment]
@Microburo Merci
Thank you, spread it.
