### ISSUE TITLE
Stopping worked since macOS Catalina

### ISSUE THREAD

**Issue by timtops** [thierryc/Sketch-Find-And-Replace#98]
Hi,

I can't say it's definitely related, but since upgrading to macOS Catalina, Find and Replace has stopped working. When I hit the shortcut keys, it launches the window but it remains blank. 

![image](https://user-images.githubusercontent.com/978182/66738416-629c5c00-ee66-11e9-9298-c0ebdd604f77.png)

In fact, on subsequent attempts, it doesn't even launch the window, Sketch just crashes. Maybe it's a Sketch/Catalina problem? Anyhow, I thought I'd mention it. :)

Thanks,
Tim

**Comment by thierryc** [comment]
It is a Catalina issue probably. A new way to manage windows maybe. 

I don't have installed Catalina yet. 
But, I will try to fix this issue. 

1st 
can you take a look to the files into this folder:

~/Library/Logs/com.bohemiancoding.sketch3/

Can you get some information about find and replace?

Best regards.
TC

**Comment by timtops** [comment]
Plugin Developer.log remains empty.

Plugin Log.log simply reads: "No WebView present. Event cannot be posted to the web UI."

It's not much! :)

Is the crash log any use?

Best of luck! 
t

**Comment by thierryc** [comment]
OK, that was I expected. Now the question is why.
I will post you a new version tomorrow to try to fix it. (private one)

**Comment by thierryc** [comment]
@timtops please can you try this version for me?

https://www.dropbox.com/sh/2sjqc41xfiou6s8/AAD6Dw7Tc8qibaoTgGFcqxjla?dl=0

**Comment by timtops** [comment]
Hi,

Apologies I didn't get to this sooner. It looks like you just pushed the
fix live though as Sketch notified me to update.

Looks like it works again!

Thanks so much! :)

**Comment by thierryc** [comment]
Nice.
Have a good day.
