### ISSUE TITLE
Cannot update to v2.5.3

### ISSUE THREAD

**Issue by JordanTranchina** [thierryc/Sketch-Find-And-Replace#99]
<img width="632" alt="Screen Shot 2019-10-16 at 8 15 12 AM" src="https://user-images.githubusercontent.com/41443492/66932869-1deefd00-efed-11e9-8f13-b3a065a12590.png">

Expected result: Clicking the update button will update the "Find and Replace" plugin.

Actual Result: Clicking the update button creates no change on the screen and does not update the plugin.

**Comment by thierryc** [comment]
To try to reproduce your bug may I can know your OS version and your sketch version too ? 

Try to install it the plugin manually. 

To install: download this file, unzip and double click on the .sketchplugin
https://github.com/thierryc/Sketch-Find-And-Replace/releases/download/v2.5.3/Find-and-replace.sketchplugin.zip

**Comment by thierryc** [comment]
To try to reproduce your bug may I can know your OS version and your sketch version too ? 

Try to install it the plugin manually. 

To install: download this file, unzip and double click on the .sketchplugin
https://github.com/thierryc/Sketch-Find-And-Replace/releases/download/v2.5.3/Find-and-replace.sketchplugin.zip

**Comment by thierryc** [comment]
Thank you.
Do you have install the plug-in manually?

**Comment by JordanTranchina** [comment]
I have not, but assume it would work. Would be great to get this fixed so we can update via Sketch though!

**Comment by JordanTranchina** [comment]
I was able to update! Looks like your last commit got it working. Thank you 👍
